using Npgsql;
using Pgvector;
using Testcontainers.PostgreSql;

namespace Contigo.Market.Tests;

/// <summary>
/// Proves the Definition of Done for task E13/F02/US01/T02 (ADR-021): the checked-in, idempotent
/// SQL script (<c>Migrations/Scripts/market.sql</c>, generated by `dotnet ef migrations script
/// --idempotent` from `src/Contigo.Market`, plus this task's own hand-added grant-model footer)
/// applies cleanly to a bare Postgres+pgvector server via plain Npgsql — no
/// <see cref="Infrastructure.MarketDbContext"/>, no EF Core runtime migrator, no
/// <see cref="Infrastructure.MarketDbContextOptions"/> anywhere in this test. This is the exact
/// artifact ADR-021's CI apply step runs against `dev`/`demo` (e.g. `psql -f`), independently of
/// the application ever starting — same shape as
/// <c>Contigo.Documents.Contracts.Tests.DocumentsContractsMigrationScriptTests</c> /
/// <c>Contigo.Suppliers.Products.Tests.SuppliersMigrationScriptTests</c>.
///
/// Also proves parent story AC-3's structural half ("no `tenant_id`, shared, read-only") directly
/// against the schema this script actually creates, and the grant-model footer's own "safe no-op
/// today, self-activates the day the CI role model provisions these roles" claim (this file's own
/// doc comment) both ways — absent and present.
/// </summary>
public sealed class MarketMigrationScriptTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("pgvector/pgvector:pg16")
        .Build();

    public Task InitializeAsync() => _postgres.StartAsync();

    public Task DisposeAsync() => _postgres.DisposeAsync().AsTask();

    /// <summary>
    /// Walks from this source file (<c>backend/tests/Contigo.Market.Tests/</c>) to the checked-in
    /// script under <c>backend/src/Contigo.Market/Migrations/Scripts/</c>.
    /// <see cref="System.Runtime.CompilerServices.CallerFilePathAttribute"/> resolves at compile
    /// time against the source tree, not the test runner's working directory or its `bin/` output,
    /// so this is stable across however `dotnet test` is invoked.
    /// </summary>
    private static string ScriptPath(
        [System.Runtime.CompilerServices.CallerFilePath] string here = "") =>
        Path.GetFullPath(Path.Combine(
            Path.GetDirectoryName(here)!, "..", "..",
            "src", "Contigo.Market", "Migrations", "Scripts", "market.sql"));

    private static async Task<string> ReadScriptAsync()
    {
        var path = ScriptPath();
        Assert.True(
            File.Exists(path),
            $"Migration script not found at {path}. Regenerate with " +
            "`dotnet ef migrations script --idempotent` from src/Contigo.Market (task " +
            "E13/F02/US01/T02), then re-apply the grant-model footer.");
        return await File.ReadAllTextAsync(path);
    }

    [Fact]
    public async Task Idempotent_script_applies_to_a_bare_postgres_and_is_safe_to_rerun()
    {
        var script = await ReadScriptAsync();
        Assert.Contains("CREATE TABLE market_record", script, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE market_embedding", script, StringComparison.Ordinal);

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        // Two applies of the same script against a server that starts with nothing but the
        // pgvector image's defaults -- no prior EF Core migrate call anywhere in this test.
        await using (var first = new NpgsqlCommand(script, connection))
        {
            await first.ExecuteNonQueryAsync();
        }

        await using (var second = new NpgsqlCommand(script, connection))
        {
            await second.ExecuteNonQueryAsync();
        }

        await using var verify = new NpgsqlCommand(
            "SELECT count(*) FROM \"__EFMigrationsHistory\" WHERE migration_id LIKE '%_Initial'", connection);
        var recordedCount = (long)(await verify.ExecuteScalarAsync())!;
        Assert.Equal(1L, recordedCount);
    }

    [Fact]
    public async Task Script_created_vector_column_is_usable_by_plain_npgsql_with_no_ef_core_involved()
    {
        var script = await ReadScriptAsync();

        await using (var setupConnection = new NpgsqlConnection(_postgres.GetConnectionString()))
        {
            await setupConnection.OpenAsync();
            await using var apply = new NpgsqlCommand(script, setupConnection);
            await apply.ExecuteNonQueryAsync();
        }

        // A bespoke data source with only the base Pgvector package's UseVector() wired in --
        // deliberately not MarketDbContextOptions -- so this proves the `vector` column the SQL
        // script created is usable by any pgvector-aware Postgres client, not something that only
        // works because of this solution's own EF Core configuration.
        var dataSourceBuilder = new NpgsqlDataSourceBuilder(_postgres.GetConnectionString());
        dataSourceBuilder.UseVector();
        await using var dataSource = dataSourceBuilder.Build();
        await using var connection = await dataSource.OpenConnectionAsync();

        const string recordId = "MKT-SCRIPT-TEST-0001";
        await using (var insertRecord = new NpgsqlCommand(
            "INSERT INTO market_record (record_id, feed_version, provider, payload_json, " +
            "provenance_label, updated_at) VALUES (@record_id, @feed_version, @provider, " +
            "@payload_json, @provenance_label, @updated_at)", connection))
        {
            insertRecord.Parameters.AddWithValue("record_id", recordId);
            insertRecord.Parameters.AddWithValue("feed_version", "v1");
            insertRecord.Parameters.AddWithValue("provider", "Internal Dataset");
            insertRecord.Parameters.AddWithValue("payload_json", NpgsqlTypes.NpgsqlDbType.Jsonb, "{}");
            insertRecord.Parameters.AddWithValue("provenance_label", "representative market data · mock feed · updated 2026-06-20");
            insertRecord.Parameters.AddWithValue("updated_at", DateTimeOffset.UtcNow);
            await insertRecord.ExecuteNonQueryAsync();
        }

        var id = Guid.NewGuid();
        var original = new float[Infrastructure.Entities.MarketEmbeddingEntity.VectorDimensions];
        for (var i = 0; i < original.Length; i++)
        {
            original[i] = i * 0.001f;
        }

        await using (var insertEmbedding = new NpgsqlCommand(
            "INSERT INTO market_embedding (id, record_id, chunk_index, chunk_text, vector, " +
            "model, created_at) VALUES " +
            "(@id, @record_id, @chunk_index, @chunk_text, @vector, @model, @created_at)",
            connection))
        {
            insertEmbedding.Parameters.AddWithValue("id", id);
            insertEmbedding.Parameters.AddWithValue("record_id", recordId);
            insertEmbedding.Parameters.AddWithValue("chunk_index", 0);
            insertEmbedding.Parameters.AddWithValue("chunk_text", "script-only round trip, no DbContext involved");
            insertEmbedding.Parameters.AddWithValue("vector", new Vector(original));
            insertEmbedding.Parameters.AddWithValue("model", "text-embedding-3-small");
            insertEmbedding.Parameters.AddWithValue("created_at", DateTimeOffset.UtcNow);
            await insertEmbedding.ExecuteNonQueryAsync();
        }

        await using var select = new NpgsqlCommand(
            "SELECT vector_dims(vector), (vector <-> vector) FROM market_embedding WHERE id = @id", connection);
        select.Parameters.AddWithValue("id", id);
        await using var reader = await select.ExecuteReaderAsync();
        Assert.True(await reader.ReadAsync());
        Assert.Equal(Infrastructure.Entities.MarketEmbeddingEntity.VectorDimensions, reader.GetInt32(0));
        Assert.Equal(0.0, reader.GetDouble(1), precision: 6);
    }

    /// <summary>
    /// Parent story AC-3's structural half, proved directly against the schema this script
    /// actually creates (not against the EF model, which could drift from what was really
    /// migrated): neither table has a <c>tenant_id</c> column, and neither table carries any
    /// Postgres RLS policy at all — a market table getting an RLS <c>tenant_isolation</c> policy
    /// the way every tenant-scoped module's own migration does would be a defect (there is no
    /// <c>tenant_id</c> for such a policy to even reference).
    /// </summary>
    [Fact]
    public async Task Neither_table_has_a_tenant_id_column_or_any_rls_policy()
    {
        var script = await ReadScriptAsync();

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();
        await using (var apply = new NpgsqlCommand(script, connection))
        {
            await apply.ExecuteNonQueryAsync();
        }

        await using (var columns = new NpgsqlCommand(
            "SELECT count(*) FROM information_schema.columns " +
            "WHERE table_name IN ('market_record', 'market_embedding') AND column_name = 'tenant_id'",
            connection))
        {
            var tenantIdColumnCount = (long)(await columns.ExecuteScalarAsync())!;
            Assert.Equal(0L, tenantIdColumnCount);
        }

        await using (var policies = new NpgsqlCommand(
            "SELECT count(*) FROM pg_policies WHERE tablename IN ('market_record', 'market_embedding')",
            connection))
        {
            var policyCount = (long)(await policies.ExecuteScalarAsync())!;
            Assert.Equal(0L, policyCount);
        }
    }

    [Fact]
    public async Task Grant_blocks_are_a_safe_no_op_when_the_ci_role_model_has_no_such_roles()
    {
        // The real CI role model today (infra/modules/postgres/main.tf: a single
        // administrator_login) -- no contigo_app/contigo_market_ingest role exists anywhere, and
        // the script's own two conditional GRANT blocks must not error (or grant anything) against
        // a server that never defines them. Idempotent_script_applies_to_a_bare_postgres_and_is_
        // safe_to_rerun already proves this (it applies the whole file, grant footer included,
        // against a fresh server with no extra roles) -- this test asserts the same fact by name.
        var script = await ReadScriptAsync();
        Assert.Contains("contigo_app", script, StringComparison.Ordinal);
        Assert.Contains("contigo_market_ingest", script, StringComparison.Ordinal);
        Assert.Contains("SELECT 1 FROM pg_roles WHERE rolname", script, StringComparison.Ordinal);

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();
        await using var apply = new NpgsqlCommand(script, connection);
        // No exception -- a real Postgres error ("role ... does not exist") would throw here if
        // the conditional guard were missing or wrong.
        await apply.ExecuteNonQueryAsync();
    }

    [Fact]
    public async Task Grant_blocks_self_activate_when_the_ci_role_model_already_provisioned_the_roles()
    {
        const string appRole = "contigo_app";
        const string ingestRole = "contigo_market_ingest";

        await using var adminConnection = new NpgsqlConnection(_postgres.GetConnectionString());
        await adminConnection.OpenAsync();

        // Simulates a later infra task having already provisioned these two roles before this
        // script runs -- the exact "when the CI role model allows it" condition the script's own
        // header comment describes.
        await using (var createRoles = new NpgsqlCommand(
            $"CREATE ROLE {appRole} LOGIN PASSWORD 'test_password_app' NOSUPERUSER NOBYPASSRLS; " +
            $"CREATE ROLE {ingestRole} LOGIN PASSWORD 'test_password_ingest' NOSUPERUSER NOBYPASSRLS;",
            adminConnection))
        {
            await createRoles.ExecuteNonQueryAsync();
        }

        var script = await ReadScriptAsync();
        await using (var apply = new NpgsqlCommand(script, adminConnection))
        {
            await apply.ExecuteNonQueryAsync();
        }

        await using (var seedRecord = new NpgsqlCommand(
            "INSERT INTO market_record (record_id, feed_version, provider, payload_json, " +
            "provenance_label, updated_at) VALUES ('MKT-GRANT-TEST', 'v1', 'Internal Dataset', " +
            "'{}', 'representative market data · mock feed · updated 2026-06-20', now())",
            adminConnection))
        {
            await seedRecord.ExecuteNonQueryAsync();
        }

        var appConnectionString = new NpgsqlConnectionStringBuilder(_postgres.GetConnectionString())
        {
            Username = appRole,
            Password = "test_password_app",
        }.ConnectionString;

        await using (var appConnection = new NpgsqlConnection(appConnectionString))
        {
            await appConnection.OpenAsync();

            await using (var read = new NpgsqlCommand("SELECT count(*) FROM market_record", appConnection))
            {
                var count = (long)(await read.ExecuteScalarAsync())!;
                Assert.Equal(1L, count);
            }

            await using var write = new NpgsqlCommand(
                "INSERT INTO market_record (record_id, feed_version, provider, payload_json, " +
                "provenance_label, updated_at) VALUES ('MKT-APP-WRITE-ATTEMPT', 'v1', " +
                "'Internal Dataset', '{}', 'x', now())", appConnection);
            // contigo_app is read-only (task objective: "grants read to the application role") --
            // an insert attempt must fail with an insufficient-privilege error, not silently no-op.
            await Assert.ThrowsAsync<PostgresException>(() => write.ExecuteNonQueryAsync());
        }

        var ingestConnectionString = new NpgsqlConnectionStringBuilder(_postgres.GetConnectionString())
        {
            Username = ingestRole,
            Password = "test_password_ingest",
        }.ConnectionString;

        await using (var ingestConnection = new NpgsqlConnection(ingestConnectionString))
        {
            await ingestConnection.OpenAsync();

            // contigo_market_ingest is the write role (task objective: "restricts writes to the
            // ingestion role") -- both a write and a read must succeed.
            await using (var write = new NpgsqlCommand(
                "INSERT INTO market_record (record_id, feed_version, provider, payload_json, " +
                "provenance_label, updated_at) VALUES ('MKT-INGEST-WRITE', 'v1', " +
                "'Internal Dataset', '{}', 'x', now())", ingestConnection))
            {
                await write.ExecuteNonQueryAsync();
            }

            await using (var read = new NpgsqlCommand("SELECT count(*) FROM market_record", ingestConnection))
            {
                var count = (long)(await read.ExecuteScalarAsync())!;
                Assert.Equal(2L, count);
            }
        }
    }
}
