using Npgsql;
using Testcontainers.PostgreSql;

namespace Raffa.Renewals.Tests;

/// <summary>
/// Proves the Definition of Done for task E09/F01/US01/T01 (story us-01-idempotent-scripts,
/// AC-1/AC-3): the checked-in, idempotent SQL script (<c>Migrations/Scripts/renewals.sql</c>,
/// generated by `dotnet ef migrations script --idempotent`) applies cleanly to a bare
/// Postgres+pgvector server via plain Npgsql — no <see cref="Infrastructure.RenewalsDbContext"/>,
/// no EF Core runtime migrator, no <see cref="Infrastructure.RenewalsDbContextOptions"/> anywhere
/// in this test. This is the exact artifact ADR-021's CI apply step (task E09/F02/US01/T02) runs
/// against `dev`/`demo` (e.g. `psql -f`), independently of the application ever starting — same
/// shape as <c>Raffa.Documents.Contracts.Tests.DocumentsContractsMigrationScriptTests</c> (same
/// `pgvector/pgvector:pg16` image, same "apply twice, still one history row" idempotency proof),
/// even though this module has no `vector` column of its own: ADR-021's deploy order runs every
/// module's script against the same shared Postgres+pgvector server, so proving against that same
/// image is the honest fixture, not a stand-in for a plain `postgres` image.
/// </summary>
public sealed class RenewalsMigrationScriptTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("pgvector/pgvector:pg16")
        .Build();

    public Task InitializeAsync() => _postgres.StartAsync();

    public Task DisposeAsync() => _postgres.DisposeAsync().AsTask();

    /// <summary>
    /// Walks from this source file (<c>backend/tests/Raffa.Renewals.Tests/</c>) to the checked-in
    /// script under <c>backend/src/Raffa.Renewals/Migrations/Scripts/</c>.
    /// <see cref="System.Runtime.CompilerServices.CallerFilePathAttribute"/> resolves at compile
    /// time against the source tree, not the test runner's working directory or its `bin/` output,
    /// so this is stable across however `dotnet test` is invoked.
    /// </summary>
    private static string ScriptPath(
        [System.Runtime.CompilerServices.CallerFilePath] string here = "") =>
        Path.GetFullPath(Path.Combine(
            Path.GetDirectoryName(here)!, "..", "..",
            "src", "Raffa.Renewals", "Migrations", "Scripts",
            "renewals.sql"));

    private static async Task<string> ReadScriptAsync()
    {
        var path = ScriptPath();
        Assert.True(
            File.Exists(path),
            $"Migration script not found at {path}. Regenerate with " +
            "`dotnet ef migrations script --idempotent` from src/Raffa.Renewals (task " +
            "E09/F01/US01/T01).");
        return await File.ReadAllTextAsync(path);
    }

    [Fact]
    public async Task Idempotent_script_applies_to_a_bare_postgres_and_is_safe_to_rerun()
    {
        var script = await ReadScriptAsync();

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        // Two applies of the same script against a server that starts with nothing but the
        // pgvector image's defaults -- no prior EF Core migrate call anywhere in this test.
        await using (var first = new NpgsqlCommand(script, connection))
        {
            await first.ExecuteNonQueryAsync();
        }

        await using (var second = new NpgsqlCommand(script, connection))
        {
            await second.ExecuteNonQueryAsync();
        }

        await using var verify = new NpgsqlCommand(
            "SELECT count(*) FROM \"__EFMigrationsHistory\" WHERE migration_id = @id", connection);
        verify.Parameters.AddWithValue("id", "20260904223135_AddTenantRowLevelSecurity");
        var recordedCount = (long)(await verify.ExecuteScalarAsync())!;
        Assert.Equal(1L, recordedCount);
    }
}
