// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Raffa.Identity.Workspace.Infrastructure;

#nullable disable

namespace Raffa.Identity.Workspace.Migrations
{
    [DbContext(typeof(IdentityWorkspaceDbContext))]
    [Migration("20260922170000_AddWorkspaceWebResearchEnabled")]
    partial class AddWorkspaceWebResearchEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("WorkspaceRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_role_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_invitation");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspace_invitation_tenant_id");

                    b.HasIndex("WorkspaceRoleId")
                        .HasDatabaseName("ix_workspace_invitation_workspace_role_id");

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_invitation_tenant_id_token_hash");

                    b.ToTable("workspace_invitation", (string)null);
                });

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkspaceRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_role_id");

                    b.Property<Guid>("WorkspaceUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_user_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_membership");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspace_membership_tenant_id");

                    b.HasIndex("WorkspaceRoleId")
                        .HasDatabaseName("ix_workspace_membership_workspace_role_id");

                    b.HasIndex("WorkspaceUserId", "WorkspaceRoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_membership_workspace_user_id_workspace_role_id");

                    b.ToTable("workspace_membership", (string)null);
                });

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspace_role_tenant_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_role_tenant_id_name");

                    b.ToTable("workspace_role", (string)null);
                });

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Industry")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("WebResearchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("web_research_enabled");

                    b.HasKey("Id")
                        .HasName("pk_workspace");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_tenant_id");

                    b.ToTable("workspace", (string)null);
                });

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workspace_user");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_workspace_user_tenant_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_user_tenant_id_email");

                    b.HasIndex("TenantId", "ExternalSubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_workspace_user_tenant_id_external_subject_id");

                    b.ToTable("workspace_user", (string)null);
                });

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceInvitation", b =>
                {
                    b.HasOne("Raffa.Identity.Workspace.Domain.WorkspaceRole", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_invitation_workspace_role_workspace_role_id");
                });

            modelBuilder.Entity("Raffa.Identity.Workspace.Domain.WorkspaceMembership", b =>
                {
                    b.HasOne("Raffa.Identity.Workspace.Domain.WorkspaceRole", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_membership_workspace_role_workspace_role_id");

                    b.HasOne("Raffa.Identity.Workspace.Domain.WorkspaceUser", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_membership_workspace_user_workspace_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
