using System.Globalization;
using System.Text;
using Contigo.AiEval.TenantFixtures;

namespace Contigo.AiEval;

/// <summary>
/// Writes <c>backend/tests/Contigo.AiEval/reports/last-run.md</c> — the per-case markdown artefact
/// task E13/F06/US01/T02 asks for ("emit a markdown report with per-case verdicts to help HITL on
/// `demo`"). Git-ignored: it is a run output, regenerated by every <c>dotnet test</c>, never a
/// reviewed source file.
///
/// <para>
/// Written for a human triaging a demo, not for a machine: the mode and the pinned clock first (so
/// nobody wonders whether a number came from a live model), then the headline
/// <c>R-EVD-03</c> counters, then coverage by intent and by tenant fixture, then the seeded
/// portfolios the expected numbers were derived from, then every case as a row, then the failures
/// and the named engine gaps in full.
/// </para>
/// </summary>
internal static class GoldenSetReport
{
    public static string Write(IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        ArgumentNullException.ThrowIfNull(outcomes);

        var path = AiEvalOptions.ReportPath;
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, Render(outcomes), Encoding.UTF8);
        return path;
    }

    private static string Render(IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        var passed = outcomes.Count(o => o.Verdict == GoldenVerdict.Pass);
        var gaps = outcomes.Count(o => o.Verdict == GoldenVerdict.KnownGap);
        var failed = outcomes.Count(o => o.Verdict == GoldenVerdict.Fail);
        var interventions = outcomes.Count(o => o.GuardIntervened);

        var report = new StringBuilder();

        report.AppendLine("# Ask V2 — AI evaluation set (golden set), last run");
        report.AppendLine();
        report.AppendLine(
            "Generated by `dotnet test backend/tests/Contigo.AiEval` (task E13/F06/US01/T02, " +
            "`ask-golden-set`; requirement R-EVD-03, spec §15.3). Regenerated on every run — " +
            "git-ignored, never reviewed as source.");
        report.AppendLine();
        report.AppendLine($"- **Mode**: {AiEvalOptions.DescribeMode()}");
        report.AppendLine(
            $"- **Run at**: {DateTimeOffset.UtcNow.ToString("u", CultureInfo.InvariantCulture)}");
        report.AppendLine($"- **Cases**: {outcomes.Count}");
        report.AppendLine($"- **Passed**: {passed}");
        report.AppendLine(
            $"- **Passed against a recorded engine gap**: {gaps} (see \"Engine gaps\" below)");
        report.AppendLine($"- **Failed**: {failed}");
        report.AppendLine(
            $"- **Guard interventions (R-EVD-03 requires 0)**: {interventions}");
        report.AppendLine();

        AppendCoverage(report, outcomes);
        AppendFixtures(report);
        AppendCases(report, outcomes);
        AppendFailures(report, outcomes);
        AppendGaps(report, outcomes);
        AppendReplies(report, outcomes);

        return report.ToString();
    }

    private static void AppendCoverage(StringBuilder report, IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        report.AppendLine("## Coverage by intent");
        report.AppendLine();
        report.AppendLine("| Intent | Cases | Pass | Known gap | Fail |");
        report.AppendLine("|---|---:|---:|---:|---:|");

        foreach (var group in outcomes
            .GroupBy(o => o.Case.Intent, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            report.AppendLine(
                $"| `{group.Key}` | {group.Count()} | {group.Count(o => o.Verdict == GoldenVerdict.Pass)} | " +
                $"{group.Count(o => o.Verdict == GoldenVerdict.KnownGap)} | " +
                $"{group.Count(o => o.Verdict == GoldenVerdict.Fail)} |");
        }

        report.AppendLine();
        report.AppendLine("## Coverage by tenant fixture and language");
        report.AppendLine();
        report.AppendLine("| Tenant fixture | Cases | it | en | Pass | Known gap | Fail |");
        report.AppendLine("|---|---:|---:|---:|---:|---:|---:|");

        foreach (var group in outcomes
            .GroupBy(o => o.Case.TenantFixture, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            report.AppendLine(
                $"| `{group.Key}` | {group.Count()} | " +
                $"{group.Count(o => o.Case.Language == "it")} | {group.Count(o => o.Case.Language == "en")} | " +
                $"{group.Count(o => o.Verdict == GoldenVerdict.Pass)} | " +
                $"{group.Count(o => o.Verdict == GoldenVerdict.KnownGap)} | " +
                $"{group.Count(o => o.Verdict == GoldenVerdict.Fail)} |");
        }

        report.AppendLine();
    }

    private static void AppendFixtures(StringBuilder report)
    {
        report.AppendLine("## Tenant fixtures the questions were asked against");
        report.AppendLine();

        foreach (var fixture in TenantFixtureCatalog.All)
        {
            report.AppendLine($"### `{fixture.Key}`");
            report.AppendLine();
            report.AppendLine(fixture.Description);
            report.AppendLine();

            if (fixture.Contracts.Count == 0)
            {
                report.AppendLine("_No contracts._");
                report.AppendLine();
                continue;
            }

            report.AppendLine("| Supplier | Type | Status | Currency | End date | Notice deadline | Annual spend | Auto-renews |");
            report.AppendLine("|---|---|---|---|---|---|---:|---|");

            foreach (var contract in fixture.Contracts)
            {
                var supplier = fixture.Suppliers
                    .FirstOrDefault(s => contract.SupplierId is { } id && s.Id == id)?.Name ?? "—";

                report.AppendLine(
                    $"| {supplier} | {contract.Type} | {contract.Status} | {contract.Currency} | " +
                    $"{Format(contract.EndDate)} | {Format(contract.CancellationDeadline)} | " +
                    $"{contract.AnnualSpend?.ToString("0", CultureInfo.InvariantCulture) ?? "—"} | " +
                    $"{(contract.AutoRenewal ? "yes" : "no")} |");
            }

            report.AppendLine();
        }
    }

    private static void AppendCases(StringBuilder report, IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        report.AppendLine("## Per-case verdicts");
        report.AppendLine();
        report.AppendLine(
            "| Case | Fixture | Intent | Lang | Question | Expected | Observed | Citations | Corpora | " +
            "Gateway calls | Guard | Verdict |");
        report.AppendLine("|---|---|---|---|---|---|---|---:|---|---:|---|---|");

        foreach (var outcome in outcomes)
        {
            report.AppendLine(
                $"| `{outcome.Case.Id}` | {outcome.Case.TenantFixture} | `{outcome.Case.Intent}` | " +
                $"{outcome.Case.Language} | {Escape(outcome.Case.Question)} | {outcome.Case.ExpectedKind} | " +
                $"{outcome.ObservedKind} | {outcome.CitationCount} | " +
                $"{(outcome.ObservedCorpora.Count == 0 ? "—" : string.Join(" ", outcome.ObservedCorpora))} | " +
                $"{outcome.GatewayCallCount} | {(outcome.GuardIntervened ? "**INTERVENED**" : "clean")} | " +
                $"{Symbol(outcome.Verdict)} |");
        }

        report.AppendLine();
    }

    private static void AppendFailures(StringBuilder report, IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        var failures = outcomes.Where(o => o.Verdict == GoldenVerdict.Fail).ToList();

        report.AppendLine("## Failures");
        report.AppendLine();

        if (failures.Count == 0)
        {
            report.AppendLine("None.");
            report.AppendLine();
            return;
        }

        foreach (var outcome in failures)
        {
            report.AppendLine($"### `{outcome.Case.Id}`");
            report.AppendLine();
            report.AppendLine($"- Question: {Escape(outcome.Case.Question)}");
            report.AppendLine(
                $"- Expected `{outcome.Case.ExpectedKind}`, observed `{outcome.ObservedKind}`");

            foreach (var failure in outcome.Failures)
            {
                report.AppendLine($"- {failure}");
            }

            report.AppendLine();
            report.AppendLine("```text");
            report.AppendLine(outcome.AnswerMarkdown);
            report.AppendLine("```");
            report.AppendLine();
        }
    }

    private static void AppendGaps(StringBuilder report, IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        report.AppendLine("## Engine gaps this run exposed");
        report.AppendLine();
        report.AppendLine(
            "Cases whose reply matched a recorded deviation from the requirement rather than the " +
            "requirement itself. Task E13/F06/US01/T02 owns `backend/tests/Contigo.AiEval/**` only " +
            "and must not change the engine, so each of these is reported here instead of fixed. " +
            "A case stops appearing the moment the engine satisfies the requirement — no JSON edit " +
            "is needed.");
        report.AppendLine();

        var gapped = outcomes.Where(o => o.Verdict == GoldenVerdict.KnownGap).ToList();
        if (gapped.Count == 0)
        {
            report.AppendLine("None — every case matched its requirement.");
            report.AppendLine();
            return;
        }

        foreach (var group in gapped
            .GroupBy(o => o.Case.KnownGap!.Id, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            report.AppendLine($"### `{group.Key}`");
            report.AppendLine();
            report.AppendLine(group.First().Case.KnownGap!.Note ?? "(no note)");
            report.AppendLine();

            foreach (var outcome in group)
            {
                report.AppendLine(
                    $"- `{outcome.Case.Id}` — {Escape(outcome.Case.Question)} → expected " +
                    $"`{outcome.Case.ExpectedKind}`, observed `{outcome.ObservedKind}`");
            }

            report.AppendLine();
        }
    }

    /// <summary>
    /// Every reply in full, verbatim, one collapsed block per case. This is the part a human
    /// actually reads before a `demo`: the per-case table above says a turn was grounded, this
    /// section is where they judge whether it was <em>useful</em> — whether the copy reads like a
    /// savings specialist, whether the citations name the right supplier, whether a decline still
    /// leaves the user somewhere to go. Collapsed with <c>&lt;details&gt;</c> so the report opens on
    /// the summary rather than on 69 replies.
    /// </summary>
    private static void AppendReplies(StringBuilder report, IReadOnlyList<GoldenCaseOutcome> outcomes)
    {
        report.AppendLine("## Every reply, verbatim");
        report.AppendLine();
        report.AppendLine(
            "One block per case, in run order. Read these before signing off a demo: the tables " +
            "above prove the replies are grounded, these show whether they are worth reading.");
        report.AppendLine();

        foreach (var outcome in outcomes)
        {
            report.AppendLine("<details>");
            report.AppendLine(
                $"<summary><code>{outcome.Case.Id}</code> — {Escape(outcome.Case.Question)} " +
                $"({Symbol(outcome.Verdict)}, <code>{outcome.ObservedKind}</code>)</summary>");
            report.AppendLine();
            report.AppendLine("```text");
            report.AppendLine(
                string.IsNullOrWhiteSpace(outcome.AnswerMarkdown) ? "(empty)" : outcome.AnswerMarkdown);
            report.AppendLine("```");
            report.AppendLine();
            report.AppendLine(
                $"- citations: {outcome.CitationCount}" +
                (outcome.ObservedCorpora.Count == 0
                    ? string.Empty
                    : $" ({string.Join(", ", outcome.ObservedCorpora)})"));
            report.AppendLine(
                "- actions: " +
                (outcome.ObservedActionHrefs.Count == 0
                    ? "none"
                    : string.Join(", ", outcome.ObservedActionHrefs.Select(href => $"`{href}`"))));
            report.AppendLine($"- audit: `{outcome.AuditAction}`, guard {(outcome.GuardIntervened ? "INTERVENED" : "clean")}");

            if (outcome.Case.Notes is { Length: > 0 } notes)
            {
                report.AppendLine($"- why this case exists: {notes}");
            }

            report.AppendLine();
            report.AppendLine("</details>");
            report.AppendLine();
        }
    }

    private static string Symbol(GoldenVerdict verdict) => verdict switch
    {
        GoldenVerdict.Pass => "pass",
        GoldenVerdict.KnownGap => "pass (known gap)",
        _ => "**FAIL**",
    };

    private static string Format(DateOnly? date) =>
        date?.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture) ?? "—";

    /// <summary>Keeps a question with a pipe or a newline from breaking the markdown table.</summary>
    private static string Escape(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);
}
