# Task E16/F01/US01/T01 (w15 Terraform). Both outputs feed
# modules/keyvault (the connection string, written as secret `acs-connection`,
# handle `acs-cs`) and modules/containerapps (the sender address, published
# as `Invitations__Mail__SenderAddress` on the API app only) via the
# environment root -- never a literal typed a second time anywhere else.
output "primary_connection_string" {
  description = "Primary connection string of this environment's Azure Communication Service resource. Sensitive -- written to Key Vault as acs-connection; never a literal in Terraform source, and not re-exported from any environment root output."
  value       = azurerm_communication_service.this.primary_connection_string
  sensitive   = true
}

output "sender_address" {
  description = "The Azure Managed Domain's default sender address (DoNotReply@<the domain's own mail_from_sender_domain attribute>). Callers must consume this output rather than hand-composing an address from the domain name -- the domain's real hostname is generated by Azure, not chosen here."
  value       = "DoNotReply@${azurerm_email_communication_service_domain.this.mail_from_sender_domain}"
}
