using Npgsql;
using Testcontainers.PostgreSql;

namespace Raffa.Chat.Tests;

/// <summary>
/// Proves the Definition of Done for task E13/F05/US01/T01 (story us-01-conversations): the
/// checked-in, idempotent SQL script (<c>Migrations/Scripts/chat.sql</c>, generated by `dotnet ef
/// migrations script --idempotent`) applies cleanly to a bare Postgres+pgvector server via plain
/// Npgsql — no <see cref="Infrastructure.ChatDbContext"/>, no EF Core runtime migrator, no
/// <see cref="Infrastructure.ChatDbContextOptions"/> anywhere in this test. This is the exact
/// artifact ADR-021's CI apply step (`.github/workflows/backend.yml`) runs against `dev`/`demo`
/// (e.g. `psql -f`), independently of the application ever starting — same shape as
/// <c>Raffa.Audit.Tests.AuditMigrationScriptTests</c> (same `pgvector/pgvector:pg16` image,
/// same "apply twice, still one history row" idempotency proof), even though this module has no
/// `vector` column of its own: ADR-021's deploy order runs every module's script against the same
/// shared Postgres+pgvector server, so proving against that same image is the honest fixture, not
/// a stand-in for a plain `postgres` image.
/// </summary>
public sealed class ChatMigrationScriptTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("pgvector/pgvector:pg16")
        .Build();

    public Task InitializeAsync() => _postgres.StartAsync();

    public Task DisposeAsync() => _postgres.DisposeAsync().AsTask();

    /// <summary>
    /// Walks from this source file (<c>backend/tests/Raffa.Chat.Tests/</c>) to the checked-in
    /// script under <c>backend/src/Raffa.Chat/Migrations/Scripts/</c>.
    /// <see cref="System.Runtime.CompilerServices.CallerFilePathAttribute"/> resolves at compile
    /// time against the source tree, not the test runner's working directory or its `bin/`
    /// output, so this is stable across however `dotnet test` is invoked.
    /// </summary>
    private static string ScriptPath(
        [System.Runtime.CompilerServices.CallerFilePath] string here = "") =>
        Path.GetFullPath(Path.Combine(
            Path.GetDirectoryName(here)!, "..", "..",
            "src", "Raffa.Chat", "Migrations", "Scripts",
            "chat.sql"));

    private static async Task<string> ReadScriptAsync()
    {
        var path = ScriptPath();
        Assert.True(
            File.Exists(path),
            $"Migration script not found at {path}. Regenerate with " +
            "`dotnet ef migrations script --idempotent` from src/Raffa.Chat (task " +
            "E13/F05/US01/T01).");
        return await File.ReadAllTextAsync(path);
    }

    [Fact]
    public async Task Idempotent_script_applies_to_a_bare_postgres_and_is_safe_to_rerun()
    {
        var script = await ReadScriptAsync();
        Assert.Contains("CREATE TABLE conversation ", script, StringComparison.Ordinal);
        Assert.Contains("CREATE TABLE conversation_message ", script, StringComparison.Ordinal);
        Assert.Contains("FORCE ROW LEVEL SECURITY", script, StringComparison.Ordinal);

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        // Two applies of the same script against a server that starts with nothing but the
        // pgvector image's defaults -- no prior EF Core migrate call anywhere in this test.
        await using (var first = new NpgsqlCommand(script, connection))
        {
            await first.ExecuteNonQueryAsync();
        }

        await using (var second = new NpgsqlCommand(script, connection))
        {
            await second.ExecuteNonQueryAsync();
        }

        await using var verify = new NpgsqlCommand(
            "SELECT count(*) FROM \"__EFMigrationsHistory\" WHERE migration_id = @id", connection);
        verify.Parameters.AddWithValue("id", "20260908205121_AddTenantRowLevelSecurity");
        var recordedCount = (long)(await verify.ExecuteScalarAsync())!;
        Assert.Equal(1L, recordedCount);
    }

    /// <summary>
    /// AC-1 "RLS policy in place" (parent story us-01-conversations) — the cross-tenant
    /// integration proof itself lands in task T02, but this task's own script must not ship a
    /// silently-missing policy. Mirrors
    /// <c>Raffa.Tenancy.Tests.TenantRlsDeployableScriptCheckTests</c>'s per-table
    /// `pg_class`/`pg_policies` assertions, scoped to this module's own two tables instead of a
    /// dynamically-discovered list (that shared project only ever queries
    /// <c>DocumentsContractsDbContext</c>'s own model, not this module's).
    /// </summary>
    [Theory]
    [InlineData("conversation")]
    [InlineData("conversation_message")]
    public async Task Deployable_script_enables_forced_row_level_security_and_a_policy(string table)
    {
        var script = await ReadScriptAsync();

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        await using (var apply = new NpgsqlCommand(script, connection))
        {
            await apply.ExecuteNonQueryAsync();
        }

        await using var flags = new NpgsqlCommand(
            "SELECT relrowsecurity, relforcerowsecurity FROM pg_class WHERE oid = to_regclass(@table)",
            connection);
        flags.Parameters.AddWithValue("table", table);
        await using (var reader = await flags.ExecuteReaderAsync())
        {
            Assert.True(await reader.ReadAsync(), $"Table \"{table}\" was not found after applying chat.sql.");
            Assert.True(reader.GetBoolean(0), $"[ADR-009] \"{table}\" is missing ROW LEVEL SECURITY.");
            Assert.True(reader.GetBoolean(1), $"[ADR-009] \"{table}\" is missing FORCE ROW LEVEL SECURITY.");
        }

        await using var policyCount = new NpgsqlCommand(
            "SELECT count(*) FROM pg_policies WHERE schemaname = 'public' AND tablename = @table",
            connection);
        policyCount.Parameters.AddWithValue("table", table);
        var count = (long)(await policyCount.ExecuteScalarAsync())!;
        Assert.True(count >= 1, $"[ADR-009] \"{table}\" has no RLS policy.");
    }
}
