// <auto-generated />
using System;
using Contigo.Renewals.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Contigo.Renewals.Migrations
{
    [DbContext(typeof(RenewalsDbContext))]
    partial class RenewalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contigo.Renewals.Domain.RenewalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_renewal_action");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_renewal_action_tenant_id");

                    b.HasIndex("TenantId", "ContractId")
                        .IsUnique()
                        .HasDatabaseName("ix_renewal_action_tenant_id_contract_id");

                    b.ToTable("renewal_action", (string)null);
                });

            modelBuilder.Entity("Contigo.Renewals.Domain.RenewalAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Milestone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("milestone");

                    b.Property<DateOnly>("MilestoneDate")
                        .HasColumnType("date")
                        .HasColumnName("milestone_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("ThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_renewal_alert");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_renewal_alert_tenant_id");

                    b.HasIndex("TenantId", "ContractId", "Milestone", "ThresholdDays")
                        .IsUnique()
                        .HasDatabaseName("ix_renewal_alert_active_tenant_contract_milestone_threshold")
                        .HasFilter("status = 'Active'");

                    b.ToTable("renewal_alert", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
