// <auto-generated />
using System;
using Contigo.Market.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Contigo.Market.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20260909011226_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contigo.Market.Infrastructure.Entities.MarketEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunk_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("record_id");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("vector");

                    b.HasKey("Id")
                        .HasName("pk_market_embedding");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("ix_market_embedding_record_id");

                    b.ToTable("market_embedding", (string)null);
                });

            modelBuilder.Entity("Contigo.Market.Infrastructure.Entities.MarketRecordEntity", b =>
                {
                    b.Property<string>("RecordId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("record_id");

                    b.Property<string>("FeedVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("feed_version");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("ProvenanceLabel")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provenance_label");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RecordId")
                        .HasName("pk_market_record");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_market_record_provider");

                    b.ToTable("market_record", (string)null);
                });

            modelBuilder.Entity("Contigo.Market.Infrastructure.Entities.MarketEmbeddingEntity", b =>
                {
                    b.HasOne("Contigo.Market.Infrastructure.Entities.MarketRecordEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_market_embedding_market_record_record_id");
                });
#pragma warning restore 612, 618
        }
    }
}
